import { expect, test } from "@playwright/test"
import { ids, operator } from "../helpers/local-supabase"
test("공개 신청이 전체·캠페인 성과와 CRM에 반영된다", async ({ page }) => { await page.goto(`/f/${ids.publicId}`); const iframe = page.locator('iframe[title="자료 신청"]'); const form = page.frameLocator('iframe[title="자료 신청"]'); await expect(iframe).toHaveAttribute("sandbox", "allow-scripts allow-forms"); await expect(form.locator("html")).toHaveAttribute("data-form-bridge", "ready"); await expect(form.getByRole("heading", { name: "자료 신청" })).toBeVisible(); await form.getByLabel("이메일").fill("e2e@example.com"); await form.getByRole("button", { name: "자료 받기" }).click(); await expect(page.getByText("신청이 완료되었습니다")).toBeVisible(); await page.goto("/login"); await page.getByLabel("이메일").fill(operator.email); await page.getByLabel("비밀번호").fill(operator.password); await page.getByRole("button", { name: "로그인" }).click(); await expect(page).toHaveURL("/"); await expect(page.locator("time").first()).toContainText(":"); await page.getByRole("link", { name: "성과" }).click(); await expect(page).toHaveURL("/performance"); await expect(page.getByRole("heading", { name: "전체 성과" })).toBeVisible(); await expect(page.getByLabel(/전체 신청 [1-9]\d*/)).toBeVisible(); await page.goto(`/campaigns/${ids.campaign}`); await expect(page.getByRole("heading", { name: "성과 요약" })).toBeVisible(); const publicFormPagePromise = page.waitForEvent("popup"); await page.getByRole("link", { name: "직접 유입 폼 열기" }).click(); const publicFormPage = await publicFormPagePromise; await expect(publicFormPage).toHaveURL(new RegExp(`/f/${ids.publicId}$`)); await publicFormPage.close(); await page.getByRole("button", { name: "4개 채널 링크 만들기" }).click(); await expect(page.getByText("인스타그램")).toBeVisible(); await expect(page.getByRole("button", { name: "직접 유입 URL 복사" })).toBeVisible(); await page.getByRole("button", { name: "입력값 보기" }).first().click(); await expect(page.getByText("e2e@example.com")).toBeVisible(); await expect(page.getByRole("dialog")).toHaveCSS("background-color", "rgb(255, 255, 255)") })

test("템플릿 목록과 캠페인 커스텀 미리보기를 제공한다", async ({ page }) => { await page.goto("/login"); await page.getByLabel("이메일").fill(operator.email); await page.getByLabel("비밀번호").fill(operator.password); await page.getByRole("button", { name: "로그인" }).click(); await page.getByRole("link", { name: "템플릿", exact: true }).click(); await expect(page).toHaveURL("/templates"); await expect(page.getByRole("cell", { name: "E2E 신청 폼" })).toBeVisible(); await page.goto("/campaigns/new"); await page.getByRole("combobox", { name: "HTML 템플릿" }).click(); await page.getByRole("option", { name: "E2E 신청 폼" }).click(); await expect(page.getByRole("combobox", { name: "HTML 템플릿" })).toContainText("E2E 신청 폼"); await page.getByLabel("공개 폼 제목").fill("커스텀 제목"); await expect(page.frameLocator('iframe[title="커스텀 신청 폼 미리보기"]').getByRole("heading", { name: "커스텀 제목" })).toBeVisible() })

test("캠페인 공개와 미공개 상태를 전환한다", async ({ page }) => { await page.goto("/login"); await page.getByLabel("이메일").fill(operator.email); await page.getByLabel("비밀번호").fill(operator.password); await page.getByRole("button", { name: "로그인" }).click(); await expect(page).toHaveURL("/"); await page.goto(`/campaigns/${ids.campaign}`); await page.getByRole("button", { name: "비공개로 전환" }).click(); await expect(page.getByText("현재 미공개 캠페인입니다")).toBeVisible(); await expect(page.getByRole("link", { name: "직접 유입 폼 열기" })).toHaveCount(0); await page.getByRole("button", { name: "캠페인 공개하기" }).click(); await expect(page.getByRole("link", { name: "직접 유입 폼 열기" })).toBeVisible() })

test("관리자 GNB에서 로그아웃한다", async ({ page }) => { await page.goto("/login"); await page.getByLabel("이메일").fill(operator.email); await page.getByLabel("비밀번호").fill(operator.password); await page.getByRole("button", { name: "로그인" }).click(); await page.getByRole("button", { name: "로그아웃" }).click(); await expect(page).toHaveURL("/login") })
test("격리 미리보기는 상위 DOM에 접근하지 못한다", async ({ page }) => { await page.goto("/login"); await page.getByLabel("이메일").fill(operator.email); await page.getByLabel("비밀번호").fill(operator.password); await page.getByRole("button", { name: "로그인" }).click(); await expect(page).toHaveURL("/"); await page.goto("/templates/new"); await page.getByLabel("템플릿 이름").fill("격리 확인"); await page.getByLabel("HTML 파일").setInputFiles({ name: "isolation.html", mimeType: "text/html", buffer: Buffer.from('<main><h1 data-form-title>자료 신청</h1><p data-form-description>이메일을 입력하세요.</p><form><label for="email">이메일</label><input id="email" name="email" type="email" required><button data-form-submit type="submit">보내기</button></form></main>') }); const frame = page.frameLocator('iframe[title="등록할 HTML 템플릿 미리보기"]'); await expect(frame.getByRole("button", { name: "보내기" })).toBeVisible(); expect(await frame.locator("body").evaluate(() => { try { void window.parent.document.body; return false } catch { return true } })).toBe(true) })
