import { beforeAll, describe, expect, it } from "vitest"
import { createClient, type SupabaseClient } from "@supabase/supabase-js"
import { anonKey, ids, localUrl, operator, otherOperator, seedLocalDatabase } from "../helpers/local-supabase"
let ownerClient: SupabaseClient, otherClient: SupabaseClient, admin: SupabaseClient
beforeAll(async () => { const seeded = await seedLocalDatabase(); admin = seeded.admin; ownerClient = createClient(localUrl, anonKey); otherClient = createClient(localUrl, anonKey); expect((await ownerClient.auth.signInWithPassword(operator)).error).toBeNull(); expect((await otherClient.auth.signInWithPassword(otherOperator)).error).toBeNull() })
describe("실제 Supabase 권한·신청·집계", () => {
  it("운영자는 본인 캠페인만 조회한다", async () => { expect((await ownerClient.from("campaigns").select("id").eq("id", ids.campaign)).data).toHaveLength(1); expect((await otherClient.from("campaigns").select("id").eq("id", ids.campaign)).data).toHaveLength(0) })
  it("방문과 동일 신청 재시도는 한 건으로 유지되고 다른 요청은 충돌한다", async () => { const visitor = crypto.randomUUID(), event = crypto.randomUUID(), key = crypto.randomUUID(); const visit = await admin.rpc("record_public_visit", { p_public_id: ids.publicId, p_link_token: null, p_visitor_id: visitor, p_event_key: event }).single(); expect(visit.error).toBeNull(); const visitData = visit.data as { visit_id: string }; const args = { p_public_id: ids.publicId, p_visit_id: visitData.visit_id, p_idempotency_key: key, p_values: { email: "integration@example.com" } }; expect(((await admin.rpc("create_public_submission", args).single()).data as { replayed: boolean }).replayed).toBe(false); expect(((await admin.rpc("create_public_submission", args).single()).data as { replayed: boolean }).replayed).toBe(true); expect((await admin.rpc("create_public_submission", { ...args, p_values: { email: "changed@example.com" } })).error?.code).toBe("P0004"); expect((await admin.from("submissions").select("id", { count: "exact" }).eq("form_id", ids.form)).count).toBe(1) })
  it("전체 성과가 실제 방문자와 신청자로 집계된다", async () => { const result = await ownerClient.rpc("get_campaign_metrics", { p_campaign_id: ids.campaign }); expect(result.error).toBeNull(); expect(result.data.overall).toMatchObject({ visits: 1, visitors: 1, submissions: 1, convertedVisitors: 1 }) })
  it("채널 링크 네 개를 생성하고 같은 토큰을 재사용한다", async () => { const first = await ownerClient.rpc("ensure_campaign_links", { p_campaign_id: ids.campaign }); expect(first.error).toBeNull(); expect(first.data).toHaveLength(4); const second = await ownerClient.rpc("ensure_campaign_links", { p_campaign_id: ids.campaign }); expect(second.error).toBeNull(); expect(second.data).toEqual(first.data) })
  it("워크스페이스 전체 성과를 집계한다", async () => { const result = await ownerClient.rpc("get_workspace_metrics"); expect(result.error).toBeNull(); expect(result.data).toMatchObject({ campaigns: 1, visits: 1, visitors: 1, submissions: 1, convertedVisitors: 1 }) })
  it("미공개 캠페인은 공개 폼 조회와 신규 방문을 차단한다", async () => { expect((await ownerClient.from("campaigns").update({ published_at: null }).eq("id", ids.campaign)).error).toBeNull(); expect((await admin.rpc("get_public_form", { p_public_id: ids.publicId }).maybeSingle()).data).toBeNull(); expect((await admin.rpc("record_public_visit", { p_public_id: ids.publicId, p_link_token: null, p_visitor_id: crypto.randomUUID(), p_event_key: crypto.randomUUID() })).error?.code).toBe("P0002"); expect((await ownerClient.from("campaigns").update({ published_at: new Date().toISOString() }).eq("id", ids.campaign)).error).toBeNull() })
})
